apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: pun-api
          image: thanapongsj/go-api:cdbabbceb4b20d1c6a6210b825be633f37e8efab
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: api.service.port
